#!/usr/bin/env python3
import os, re

ROOT = "/Users/apple/Downloads/ICAI-CAGPT"
EXTS = {".ts", ".tsx"}
EXCLUDE_DIRS = {"node_modules", "dist", ".git"}

# Ordered replacements (most specific first)
REPLACEMENTS = [
    # Service/product names
    ("LucaSearch", "CA GPT Search"),
    ("Luca Financial Intelligence, Inc.", "ICAI CAGPT"),
    ("Luca Financial Intelligence", "ICAI CAGPT"),
    ("Luca CPA AI Launched", "CA GPT Launched"),
    ("Luca Agent", "CA GPT Agent"),
    ("Luca Accounting", "CA GPT Accounting"),
    ("Luca EasyLoans", "CA GPT Loans"),
    ("Luca Exclusive", "CA GPT Exclusive"),
    ("Luca Exclusives", "CA GPT Exclusives"),
    ("Luca Admin", "CA GPT Admin"),
    ("Luca Team", "CA GPT Team"),
    ("Luca Blog", "CA GPT Blog"),
    ("Luca Documentation", "CA GPT Documentation"),
    ("Luca API", "CA GPT API"),
    ("Luca Output", "CA GPT Output"),
    ("Luca User", "CA GPT User"),
    ("Luca ★", "CA GPT ★"),
    # Sentence patterns
    ("Generated by Luca AI", "Generated by CA GPT"),
    ("Generated by Luca", "Generated by CA GPT"),
    ("Prepared by:** Luca - Accounting Superintelligence", "Prepared by:** CA GPT - Accounting Superintelligence"),
    ("Introducing Luca: Accounting Superintelligence", "Introducing CA GPT: Accounting Superintelligence"),
    ("Introducing Luca:", "Introducing CA GPT:"),
    ("Ask Luca About Loans", "Ask CA GPT About Loans"),
    ("Welcome to Luca!", "Welcome to CA GPT!"),
    ("Sign in to continue to Luca", "Sign in to continue to CA GPT"),
    ("Get started with Luca for free", "Get started with CA GPT for free"),
    ("Your Luca account details", "Your CA GPT account details"),
    ("Start Using Luca", "Start Using CA GPT"),
    ("Start using Luca", "Start using CA GPT"),
    ("Learn About Luca", "Learn About CA GPT"),
    ("Why Luca?", "Why CA GPT?"),
    # Possessives
    ("Luca's", "CA GPT's"),
    ("luca's", "CA GPT's"),
    # Generic "Luca" standalone occurrences (catch-all after specific ones above)
    ('"Luca"', '"CA GPT"'),
    (">Luca<", ">CA GPT<"),
    ("'Luca'", "'CA GPT'"),
    # In comments
    ("// Luca", "// CA GPT"),
    ("* Luca", "* CA GPT"),
    # Remaining standalone after all above
    (" Luca ", " CA GPT "),
    (" Luca.", " CA GPT."),
    (" Luca,", " CA GPT,"),
    (" Luca!", " CA GPT!"),
    (" Luca?", " CA GPT?"),
    (" Luca:", " CA GPT:"),
    (" Luca)", " CA GPT)"),
    (" Luca\n", " CA GPT\n"),
    ("\nLuca ", "\nCA GPT "),
    ("\nLuca\n", "\nCA GPT\n"),
    # LUCA uppercase
    ('"LUCA"', '"CA GPT"'),
    (">LUCA<", ">CA GPT<"),
]

def process_file(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()
    original = content
    for old, new in REPLACEMENTS:
        content = content.replace(old, new)
    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  Updated: {path[len(ROOT):]}")

for dirpath, dirnames, filenames in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
    for fname in filenames:
        if os.path.splitext(fname)[1] in EXTS:
            process_file(os.path.join(dirpath, fname))

print("Done.")
