INSERT INTO deliverable_templates (id, owner_user_id, name, description, type, category, content_template, variable_schema, is_system, is_default, is_public, usage_count)
VALUES
  ('sys-tax-memo', NULL, 'Tax Strategy Memo', 'Comprehensive tax planning and strategy advisory memo for clients', 'tax_memo', 'tax',
   '# Tax Strategy Memo\n\n**Prepared for:** {{client_name}}\n**Entity Type:** {{entity_type}}\n**Tax Year:** {{tax_year}}\n**Jurisdiction:** {{jurisdiction}}\n\n---\n\n## Executive Summary\n\nThis memo provides a comprehensive analysis of the tax position and strategic recommendations for {{client_name}} operating as a {{entity_type}} in {{jurisdiction}} for the {{tax_year}} tax year.\n\n## Current Tax Position\n\nBased on a gross income of ${{income_amount}}, the following analysis applies.\n\n### Federal Tax Considerations\n[AI analysis of federal tax implications]\n\n### State Considerations\n[AI analysis for {{jurisdiction}}]\n\n## Strategic Recommendations\n\n1. [AI recommendation 1]\n2. [AI recommendation 2]\n3. [AI recommendation 3]\n\n## Citations\n\n- Internal Revenue Code applicable sections\n- {{jurisdiction}} tax code references\n\n---\n*Generated by CA GPT*',
   '{"type":"object","properties":{"client_name":{"type":"string","title":"Client Name"},"entity_type":{"type":"string","title":"Entity Type","enum":["sole_proprietor","llc","s-corp","c-corp","partnership"]},"tax_year":{"type":"string","title":"Tax Year"},"income_amount":{"type":"string","title":"Income Amount"},"jurisdiction":{"type":"string","title":"Jurisdiction"}},"required":["client_name","entity_type","tax_year"]}',
   true, true, true, 0),

  ('sys-audit-plan', NULL, 'Audit Plan', 'Structured audit planning document with risk assessment and procedures', 'audit_plan', 'audit',
   '# Audit Plan\n\n**Client:** {{client_name}}\n**Entity Type:** {{entity_type}}\n**Period:** {{tax_year}}\n\n---\n\n## 1. Engagement Overview\n[AI engagement overview]\n\n## 2. Risk Assessment\n[AI risk assessment]\n\n## 3. Materiality\n[AI materiality thresholds]\n\n## 4. Audit Procedures\n[AI procedures]\n\n## 5. Timeline\n[AI timeline]\n\n---\n*Generated by CA GPT*',
   '{"type":"object","properties":{"client_name":{"type":"string","title":"Client Name"},"entity_type":{"type":"string","title":"Entity Type"},"tax_year":{"type":"string","title":"Audit Period"},"jurisdiction":{"type":"string","title":"Jurisdiction"}},"required":["client_name","tax_year"]}',
   true, false, true, 0),

  ('sys-compliance-checklist', NULL, 'Compliance Checklist', 'Regulatory compliance verification checklist with action items', 'checklist', 'compliance',
   '# Compliance Checklist\n\n**Client:** {{client_name}}\n**Entity:** {{entity_type}}\n**Year:** {{tax_year}}\n**Jurisdiction:** {{jurisdiction}}\n\n---\n\n## Filing Requirements\n- [ ] Federal income tax return\n- [ ] State income tax return ({{jurisdiction}})\n- [ ] Estimated tax payments\n- [ ] Payroll tax filings\n\n## Entity-Specific Requirements\n[AI checklist for {{entity_type}}]\n\n## Deadlines\n[AI deadline table]\n\n---\n*Generated by CA GPT*',
   '{"type":"object","properties":{"client_name":{"type":"string","title":"Client Name"},"entity_type":{"type":"string","title":"Entity Type"},"tax_year":{"type":"string","title":"Tax Year"},"income_amount":{"type":"string","title":"Income Amount"},"jurisdiction":{"type":"string","title":"Jurisdiction"}},"required":["client_name","tax_year","jurisdiction"]}',
   true, false, true, 0),

  ('sys-board-presentation', NULL, 'Board Presentation', 'Executive-level presentation with financial insights and strategic outlook', 'board_presentation', 'advisory',
   '# Board Presentation: Financial Review\n\n**Company:** {{client_name}}\n**Period:** {{tax_year}}\n\n---\n\n## Financial Highlights\n[AI financial highlights]\n\n## Tax Position Summary\n- Total income: ${{income_amount}}\n- Entity: {{entity_type}}\n- Jurisdiction: {{jurisdiction}}\n\n## Strategic Assessment\n[AI strategic insights]\n\n## Recommendations\n[AI board recommendations]\n\n---\n*Prepared by CA GPT for Board Review*',
   '{"type":"object","properties":{"client_name":{"type":"string","title":"Company Name"},"entity_type":{"type":"string","title":"Entity Type"},"tax_year":{"type":"string","title":"Fiscal Period"},"income_amount":{"type":"string","title":"Revenue Amount"},"jurisdiction":{"type":"string","title":"Primary Jurisdiction"}},"required":["client_name","tax_year"]}',
   true, false, true, 0),

  ('sys-client-letter', NULL, 'Client Advisory Letter', 'Professional advisory letter with personalized recommendations', 'client_letter', 'advisory',
   '# Advisory Letter\n\n**To:** {{client_name}}\n**From:** CA GPT Advisory Team\n**Re:** {{tax_year}} Tax & Financial Advisory\n\n---\n\nDear {{client_name}},\n\nWe provide this advisory letter summarizing our analysis and recommendations regarding your {{entity_type}} operations in {{jurisdiction}} for the {{tax_year}} period.\n\n## Summary of Analysis\n[AI analysis summary based on income of ${{income_amount}}]\n\n## Key Findings\n[AI findings]\n\n## Recommendations\n[AI recommendations]\n\n## Next Steps\nWe recommend scheduling a follow-up consultation.\n\nSincerely,\nCA GPT Advisory Team\n\n---\n*This letter is for informational purposes and does not constitute legal or tax advice.*',
   '{"type":"object","properties":{"client_name":{"type":"string","title":"Client Name"},"entity_type":{"type":"string","title":"Entity Type"},"tax_year":{"type":"string","title":"Tax Year"},"income_amount":{"type":"string","title":"Income Amount"},"jurisdiction":{"type":"string","title":"Jurisdiction"}},"required":["client_name","tax_year"]}',
   true, false, true, 0)

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  type = EXCLUDED.type,
  category = EXCLUDED.category,
  content_template = EXCLUDED.content_template,
  variable_schema = EXCLUDED.variable_schema,
  is_system = EXCLUDED.is_system,
  is_public = EXCLUDED.is_public,
  updated_at = NOW();
