/**
 * Excel Orchestrator Service - AI-Enhanced Version
 * Comprehensive Excel integration with AI-driven formula generation
 * Supports: Advanced formulas (XLOOKUP, INDEX-MATCH), VBA macros, financial models
 */

import ExcelJS from 'exceljs';
import { FinancialSolverService } from './financialSolvers';
import { aiFormulaGenerator, FormulaGenerationRequest } from './excel/aiFormulaGenerator';
import { vbaGenerator, VBAGenerationRequest } from './excel/vbaGenerator';
import { financialModelTemplates } from './excel/financialModelTemplates';
import { adHocTemplateGenerator, AdHocTemplateRequest } from './excel/adHocTemplateGenerator';

export interface SpreadsheetRequest {
  operation: 'create' | 'modify' | 'calculate' | 'analyze';
  data?: any[][];
  formulas?: FormulaDefinition[];
  tables?: TableDefinition[];
  charts?: ChartDefinition[];
  formatting?: FormattingOptions;
  calculations?: CalculationRequest[];
}

export interface FormulaDefinition {
  cell: string;
  formula: string;
  description?: string;
}

export interface TableDefinition {
  name: string;
  range: string;
  headers: string[];
  data: any[][];
  totals?: boolean;
  style?: 'light' | 'medium' | 'dark';
}

export interface ChartDefinition {
  type: 'line' | 'bar' | 'pie' | 'scatter' | 'area';
  title: string;
  dataRange: string;
  position?: { col: number; row: number };
}

export interface FormattingOptions {
  numberFormat?: string;
  currency?: string;
  dateFormat?: string;
  conditionalFormatting?: ConditionalFormat[];
}

export interface ConditionalFormat {
  range: string;
  rule: 'greaterThan' | 'lessThan' | 'between' | 'dataBar' | 'colorScale';
  values?: number[];
  colors?: string[];
}

export interface CalculationRequest {
  type: 'tax' | 'npv' | 'irr' | 'depreciation' | 'amortization' | 'loan' | 'custom';
  inputs: Record<string, number | string>;
  outputLocation?: string;
}

export interface ExcelOperationResult {
  workbook: ExcelJS.Workbook;
  buffer: Buffer;
  summary: string;
  formulasUsed: FormulaDefinition[];
  tablesCreated: string[];
}

export class ExcelOrchestrator {
  private financialSolver: FinancialSolverService;

  constructor() {
    this.financialSolver = new FinancialSolverService();
  }

  /**
   * AI-enhanced: Parse natural language and generate appropriate Excel content
   * Now uses AI to understand complex requests and generate advanced formulas
   */
  async parseUserRequest(userQuery: string, uploadedData?: any[][]): Promise<SpreadsheetRequest> {
    const request: SpreadsheetRequest = {
      operation: 'create',
      data: uploadedData,
      tables: [],
      formulas: [],
      calculations: []
    };

    // Use AI to analyze user intent and detect required formulas/models
    const queryLower = userQuery.toLowerCase();
    
    // Detect financial model requests
    if (queryLower.match(/dcf|discounted cash flow|valuation/i)) {
      request.calculations?.push({
        type: 'custom',
        inputs: { modelType: 'dcf' },
        outputLocation: 'A1'
      });
    }

    if (queryLower.match(/lbo|leveraged buyout/i)) {
      request.calculations?.push({
        type: 'custom',
        inputs: { modelType: 'lbo' },
        outputLocation: 'A1'
      });
    }

    if (queryLower.match(/3-?statement|three statement/i)) {
      request.calculations?.push({
        type: 'custom',
        inputs: { modelType: '3-statement' },
        outputLocation: 'A1'
      });
    }

    // Detect formula generation requests
    if (queryLower.match(/xlookup|vlookup|lookup/i)) {
      request.formulas?.push({
        cell: 'B2',
        formula: '', // Will be generated by AI
        description: 'Lookup formula'
      });
    }

    if (queryLower.match(/index.*match|index-match/i)) {
      request.formulas?.push({
        cell: 'B2',
        formula: '', // Will be generated by AI
        description: 'INDEX-MATCH formula'
      });
    }

    if (queryLower.match(/sumifs?|countifs?|averageifs?/i)) {
      request.formulas?.push({
        cell: 'B2',
        formula: '', // Will be generated by AI
        description: 'Conditional aggregation formula'
      });
    }

    // Extract calculation requirements (existing logic)
    if (queryLower.includes('tax')) {
      request.calculations?.push({
        type: 'tax',
        inputs: {},
        outputLocation: 'B10'
      });
    }

    if (queryLower.match(/npv|net present value/i)) {
      request.calculations?.push({
        type: 'npv',
        inputs: {},
        outputLocation: 'B15'
      });
    }

    if (queryLower.match(/irr|internal rate of return/i)) {
      request.calculations?.push({
        type: 'irr',
        inputs: {},
        outputLocation: 'B20'
      });
    }

    return request;
  }

  /**
   * Generate complete financial model from AI prompt
   */
  async generateFinancialModel(modelType: string, params: any): Promise<ExcelOperationResult> {
    let workbook: ExcelJS.Workbook;

    switch (modelType.toLowerCase()) {
      case 'dcf':
        workbook = await financialModelTemplates.generateDCFModel({
          companyName: params.companyName || 'Company',
          forecastYears: params.years || 5,
          wacc: params.wacc,
          terminalGrowth: params.terminalGrowth
        });
        break;
      
      case '3-statement':
        workbook = await financialModelTemplates.generate3StatementModel({
          companyName: params.companyName || 'Company',
          years: params.years || 5
        });
        break;
      
      case 'budget':
        workbook = await financialModelTemplates.generateBudgetTemplate({
          businessName: params.businessName || 'Business',
          fiscalYear: params.year || new Date().getFullYear(),
          departments: params.departments
        });
        break;
      
      default:
        throw new Error(`Unknown model type: ${modelType}`);
    }

    const buffer = await workbook.xlsx.writeBuffer();

    return {
      workbook,
      buffer: Buffer.from(buffer),
      summary: `${modelType.toUpperCase()} model generated with complete formulas and structure`,
      formulasUsed: [],
      tablesCreated: workbook.worksheets.map(ws => ws.name)
    };
  }

  /**
   * Generate ad-hoc custom Excel template from natural language
   * Can create ANY business template, not just financial models
   */
  async generateAdHocTemplate(request: AdHocTemplateRequest): Promise<ExcelOperationResult> {
    console.log('[ExcelOrchestrator] Generating ad-hoc template:', request.description);
    
    const workbook = await adHocTemplateGenerator.generateTemplate(request);
    const buffer = await workbook.xlsx.writeBuffer();

    return {
      workbook,
      buffer: Buffer.from(buffer),
      summary: `Custom template generated: ${request.description}`,
      formulasUsed: [],
      tablesCreated: workbook.worksheets.map(ws => ws.name)
    };
  }

  /**
   * Generate advanced Excel formula using AI
   */
  async generateAdvancedFormula(
    prompt: string,
    context?: {
      sheetStructure?: any;
      existingFormulas?: string[];
    }
  ): Promise<string> {
    const request: FormulaGenerationRequest = {
      prompt,
      context,
      complexity: 'advanced'
    };

    const result = await aiFormulaGenerator.generateFormula(request);
    return result.formula;
  }

  /**
   * Generate VBA macro from natural language
   */
  async generateVBAMacro(
    prompt: string,
    macroType: 'subroutine' | 'function' | 'userform' | 'event' | 'automation' = 'subroutine'
  ): Promise<string> {
    const request: VBAGenerationRequest = {
      prompt,
      macroType,
      complexity: 'advanced'
    };

    const result = await vbaGenerator.generateMacro(request);
    return vbaGenerator.exportVBAModule(result);
  }

  /**
   * Generate complete financial model VBA automation
   */
  async generateModelAutomation(modelType: string): Promise<string> {
    const macros = await vbaGenerator.generateFinancialModelMacros(modelType);
    
    return macros.map(macro => `
' ${macro.description}
' Category: ${macro.category}

${macro.code}

`).join('\n\n');
  }

  /**
   * Create comprehensive Excel workbook with calculations
   */
  async createCalculationWorkbook(request: SpreadsheetRequest): Promise<ExcelOperationResult> {
    const workbook = new ExcelJS.Workbook();
    
    // Set workbook properties
    workbook.creator = 'ICAI CAGPT';
    workbook.lastModifiedBy = 'ICAI CAGPT';
    workbook.created = new Date();
    workbook.modified = new Date();
    
    const sheet = workbook.addWorksheet('Financial Analysis', {
      properties: { tabColor: { argb: 'FF1E40AF' } }
    });

    const formulasUsed: FormulaDefinition[] = [];
    const tablesCreated: string[] = [];
    let currentRow = 4; // Start after header rows

    // Add professional header with branding
    this.addHeader(sheet);

    // Process calculations
    if (request.calculations) {
      for (const calc of request.calculations) {
        const result = await this.executeCalculation(calc, sheet, currentRow);
        formulasUsed.push(...result.formulas);
        currentRow = result.nextRow;
      }
    }

    // Process tables
    if (request.tables) {
      for (const table of request.tables) {
        this.createTable(sheet, table, currentRow);
        tablesCreated.push(table.name);
        currentRow += table.data.length + 4;
      }
    }

    // Process raw data if provided
    if (request.data && request.data.length > 0) {
      this.addDataWithHeaders(sheet, request.data, currentRow);
      currentRow += request.data.length + 3;
    }

    // Apply formatting
    this.applyStandardFormatting(sheet, request.formatting);

    const workbookBuffer = await workbook.xlsx.writeBuffer();

    return {
      workbook,
      buffer: Buffer.from(workbookBuffer),
      summary: this.generateSummary(formulasUsed, tablesCreated, request),
      formulasUsed,
      tablesCreated
    };
  }

  /**
   * Execute specific calculation and add to worksheet
   */
  private async executeCalculation(
    calc: CalculationRequest,
    sheet: ExcelJS.Worksheet,
    startRow: number
  ): Promise<{ formulas: FormulaDefinition[]; nextRow: number }> {
    const formulas: FormulaDefinition[] = [];
    let currentRow = startRow;

    switch (calc.type) {
      case 'tax':
        return this.addTaxCalculation(sheet, calc.inputs, currentRow);
      case 'npv':
        return this.addNPVCalculation(sheet, calc.inputs, currentRow);
      case 'irr':
        return this.addIRRCalculation(sheet, calc.inputs, currentRow);
      case 'depreciation':
        return this.addDepreciationSchedule(sheet, calc.inputs, currentRow);
      case 'amortization':
        return this.addAmortizationSchedule(sheet, calc.inputs, currentRow);
      case 'loan':
        return this.addLoanCalculation(sheet, calc.inputs, currentRow);
      default:
        return { formulas, nextRow: currentRow };
    }
  }

  /**
   * Add tax calculation with formulas
   */
  private addTaxCalculation(
    sheet: ExcelJS.Worksheet,
    inputs: Record<string, any>,
    startRow: number
  ): { formulas: FormulaDefinition[]; nextRow: number } {
    const formulas: FormulaDefinition[] = [];
    let row = startRow;

    // Title
    const titleCell = sheet.getCell(`A${row}`);
    titleCell.value = 'Tax Calculation';
    titleCell.font = { bold: true, size: 14, color: { argb: 'FF0066CC' } };
    titleCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE6F0FF' }
    };
    row += 2;

    // Revenue
    sheet.getCell(`A${row}`).value = 'Revenue';
    sheet.getCell(`B${row}`).value = inputs.revenue || 1000000;
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    row++;

    // Expenses
    sheet.getCell(`A${row}`).value = 'Expenses';
    sheet.getCell(`B${row}`).value = inputs.expenses || 600000;
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    row++;

    // Taxable Income Formula
    sheet.getCell(`A${row}`).value = 'Taxable Income';
    sheet.getCell(`B${row}`).value = { formula: `B${startRow + 2}-B${startRow + 3}` };
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    formulas.push({
      cell: `B${row}`,
      formula: `B${startRow + 2}-B${startRow + 3}`,
      description: 'Revenue minus Expenses'
    });
    row++;

    // Federal Tax Rate
    sheet.getCell(`A${row}`).value = 'Federal Tax Rate';
    sheet.getCell(`B${row}`).value = 0.21;
    sheet.getCell(`B${row}`).numFmt = '0.00%';
    row++;

    // State Tax Rate
    sheet.getCell(`A${row}`).value = 'State Tax Rate (Avg)';
    sheet.getCell(`B${row}`).value = 0.06;
    sheet.getCell(`B${row}`).numFmt = '0.00%';
    row++;

    // Federal Tax Calculated
    sheet.getCell(`A${row}`).value = 'Federal Tax';
    sheet.getCell(`B${row}`).value = { formula: `B${row - 2}*B${row - 1}` };
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    formulas.push({
      cell: `B${row}`,
      formula: `B${row - 2}*B${row - 1}`,
      description: 'Taxable Income × Federal Rate'
    });
    row++;

    // State Tax Calculated
    sheet.getCell(`A${row}`).value = 'State Tax';
    sheet.getCell(`B${row}`).value = { formula: `B${row - 3}*B${row - 2}` };
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    formulas.push({
      cell: `B${row}`,
      formula: `B${row - 3}*B${row - 2}`,
      description: 'Taxable Income × State Rate'
    });
    row++;

    // Total Tax
    sheet.getCell(`A${row}`).value = 'Total Tax';
    sheet.getCell(`A${row}`).font = { bold: true };
    sheet.getCell(`B${row}`).value = { formula: `B${row - 1}+B${row - 2}` };
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    sheet.getCell(`B${row}`).font = { bold: true };
    sheet.getCell(`B${row}`).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFFEB3B' }
    };
    formulas.push({
      cell: `B${row}`,
      formula: `B${row - 1}+B${row - 2}`,
      description: 'Federal Tax + State Tax'
    });
    row++;

    // Effective Tax Rate
    sheet.getCell(`A${row}`).value = 'Effective Tax Rate';
    sheet.getCell(`B${row}`).value = { formula: `B${row - 1}/B${row - 5}` };
    sheet.getCell(`B${row}`).numFmt = '0.00%';
    formulas.push({
      cell: `B${row}`,
      formula: `B${row - 1}/B${row - 5}`,
      description: 'Total Tax ÷ Taxable Income'
    });

    return { formulas, nextRow: row + 3 };
  }

  /**
   * Add NPV calculation - Professional styled
   */
  private addNPVCalculation(
    sheet: ExcelJS.Worksheet,
    inputs: Record<string, any>,
    startRow: number
  ): { formulas: FormulaDefinition[]; nextRow: number } {
    const formulas: FormulaDefinition[] = [];
    let row = startRow;

    // Professional Title with styling
    sheet.mergeCells(`A${row}:E${row}`);
    const titleCell = sheet.getCell(`A${row}`);
    titleCell.value = '📊 Net Present Value (NPV) Analysis';
    titleCell.font = { bold: true, size: 16, color: { argb: 'FFFFFFFF' } };
    titleCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1E40AF' } // Professional blue
    };
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
    sheet.getRow(row).height = 30;
    row += 2;

    // Input Section Header
    sheet.mergeCells(`A${row}:B${row}`);
    const inputHeaderCell = sheet.getCell(`A${row}`);
    inputHeaderCell.value = '📥 Input Parameters';
    inputHeaderCell.font = { bold: true, size: 12, color: { argb: 'FF1E40AF' } };
    inputHeaderCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E7FF' } // Light blue
    };
    row++;

    // Initial Investment
    sheet.getCell(`A${row}`).value = 'Initial Investment';
    sheet.getCell(`A${row}`).font = { bold: true };
    const initialInvestment = inputs.initialInvestment || -100000;
    sheet.getCell(`B${row}`).value = initialInvestment;
    sheet.getCell(`B${row}`).numFmt = '"$"#,##0.00';
    sheet.getCell(`B${row}`).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFFF3CD' } // Light yellow for inputs
    };
    const investmentRow = row;
    row++;

    // Discount Rate
    sheet.getCell(`A${row}`).value = 'Discount Rate';
    sheet.getCell(`A${row}`).font = { bold: true };
    const discountRate = inputs.discountRate || 0.10;
    sheet.getCell(`B${row}`).value = discountRate;
    sheet.getCell(`B${row}`).numFmt = '0.00%';
    sheet.getCell(`B${row}`).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFFF3CD' } // Light yellow for inputs
    };
    const discountRow = row;
    row++;

    // Number of Years
    const cashFlows = inputs.cashFlows || [30000, 30000, 30000, 30000, 30000];
    sheet.getCell(`A${row}`).value = 'Investment Period';
    sheet.getCell(`A${row}`).font = { bold: true };
    sheet.getCell(`B${row}`).value = `${cashFlows.length} Years`;
    row += 2;

    // Cash Flow Table Header
    sheet.mergeCells(`A${row}:D${row}`);
    const cfHeaderCell = sheet.getCell(`A${row}`);
    cfHeaderCell.value = '💰 Cash Flow Analysis';
    cfHeaderCell.font = { bold: true, size: 12, color: { argb: 'FF1E40AF' } };
    cfHeaderCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E7FF' }
    };
    row++;

    // Table Headers
    const headers = ['Year', 'Cash Flow', 'Discount Factor', 'Present Value'];
    headers.forEach((header, idx) => {
      const cell = sheet.getCell(row, idx + 1);
      cell.value = header;
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF374151' } // Dark gray
      };
      cell.alignment = { horizontal: 'center' };
      cell.border = {
        top: { style: 'thin' },
        bottom: { style: 'thin' },
        left: { style: 'thin' },
        right: { style: 'thin' }
      };
    });
    row++;

    const cashFlowStartRow = row;
    let totalPV = 0;
    
    for (let year = 0; year < cashFlows.length; year++) {
      const isEvenRow = year % 2 === 0;
      const rowBgColor = isEvenRow ? 'FFF9FAFB' : 'FFFFFFFF';
      
      // Year
      const yearCell = sheet.getCell(`A${row}`);
      yearCell.value = year + 1;
      yearCell.alignment = { horizontal: 'center' };
      yearCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowBgColor } };
      yearCell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
      
      // Cash Flow
      const cfCell = sheet.getCell(`B${row}`);
      cfCell.value = cashFlows[year];
      cfCell.numFmt = '"$"#,##0.00';
      cfCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowBgColor } };
      cfCell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
      
      // Discount Factor formula: 1/(1+r)^n
      const dfFormula = `1/(1+$B$${discountRow})^A${row}`;
      const dfCell = sheet.getCell(`C${row}`);
      dfCell.value = { formula: dfFormula };
      dfCell.numFmt = '0.0000';
      dfCell.alignment = { horizontal: 'center' };
      dfCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowBgColor } };
      dfCell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
      formulas.push({ cell: `C${row}`, formula: dfFormula, description: `Discount factor Year ${year + 1}` });
      
      // Present Value formula: CF * DF
      const pvFormula = `B${row}*C${row}`;
      const pvCell = sheet.getCell(`D${row}`);
      pvCell.value = { formula: pvFormula };
      pvCell.numFmt = '"$"#,##0.00';
      pvCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowBgColor } };
      pvCell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
      formulas.push({ cell: `D${row}`, formula: pvFormula, description: `Present Value Year ${year + 1}` });
      
      row++;
    }

    // Sum of Present Values Row
    sheet.getCell(`A${row}`).value = 'Total PV of Cash Flows';
    sheet.getCell(`A${row}`).font = { bold: true };
    sheet.mergeCells(`A${row}:C${row}`);
    const sumPvFormula = `SUM(D${cashFlowStartRow}:D${row - 1})`;
    const sumCell = sheet.getCell(`D${row}`);
    sumCell.value = { formula: sumPvFormula };
    sumCell.numFmt = '"$"#,##0.00';
    sumCell.font = { bold: true };
    sumCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE5E7EB' } };
    sumCell.border = { top: { style: 'medium' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
    formulas.push({ cell: `D${row}`, formula: sumPvFormula, description: 'Sum of all Present Values' });
    row += 2;

    // Final NPV Result - Highlighted
    sheet.mergeCells(`A${row}:C${row}`);
    const npvLabelCell = sheet.getCell(`A${row}`);
    npvLabelCell.value = '🎯 NET PRESENT VALUE (NPV)';
    npvLabelCell.font = { bold: true, size: 14, color: { argb: 'FFFFFFFF' } };
    npvLabelCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF059669' } // Green
    };
    npvLabelCell.alignment = { horizontal: 'center', vertical: 'middle' };
    
    const npvFormula = `B${investmentRow}+D${row - 2}`;
    const npvCell = sheet.getCell(`D${row}`);
    npvCell.value = { formula: npvFormula };
    npvCell.numFmt = '"$"#,##0.00';
    npvCell.font = { bold: true, size: 14, color: { argb: 'FFFFFFFF' } };
    npvCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF059669' } // Green
    };
    npvCell.alignment = { horizontal: 'center', vertical: 'middle' };
    npvCell.border = {
      top: { style: 'medium' },
      bottom: { style: 'medium' },
      left: { style: 'medium' },
      right: { style: 'medium' }
    };
    sheet.getRow(row).height = 28;
    formulas.push({ cell: `D${row}`, formula: npvFormula, description: 'Net Present Value = Initial Investment + Sum of PVs' });
    row += 2;

    // Decision Box
    sheet.mergeCells(`A${row}:D${row}`);
    const decisionCell = sheet.getCell(`A${row}`);
    decisionCell.value = '✅ Decision: If NPV > 0, the investment is financially viable';
    decisionCell.font = { italic: true, size: 11, color: { argb: 'FF374151' } };
    decisionCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF0FDF4' } // Very light green
    };
    decisionCell.alignment = { horizontal: 'center' };
    row += 2;

    // Set column widths
    sheet.getColumn(1).width = 25;
    sheet.getColumn(2).width = 18;
    sheet.getColumn(3).width = 18;
    sheet.getColumn(4).width = 18;

    return { formulas, nextRow: row + 2 };
  }

  /**
   * Add IRR calculation - Professional styled
   */
  private addIRRCalculation(
    sheet: ExcelJS.Worksheet,
    inputs: Record<string, any>,
    startRow: number
  ): { formulas: FormulaDefinition[]; nextRow: number } {
    const formulas: FormulaDefinition[] = [];
    let row = startRow;

    // Professional Title
    sheet.mergeCells(`A${row}:C${row}`);
    const titleCell = sheet.getCell(`A${row}`);
    titleCell.value = '📈 Internal Rate of Return (IRR) Analysis';
    titleCell.font = { bold: true, size: 16, color: { argb: 'FFFFFFFF' } };
    titleCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF7C3AED' } // Purple
    };
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
    sheet.getRow(row).height = 30;
    row += 2;

    // Table Headers
    const headers = ['Period', 'Cash Flow'];
    headers.forEach((header, idx) => {
      const cell = sheet.getCell(row, idx + 1);
      cell.value = header;
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF374151' }
      };
      cell.alignment = { horizontal: 'center' };
      cell.border = {
        top: { style: 'thin' },
        bottom: { style: 'thin' },
        left: { style: 'thin' },
        right: { style: 'thin' }
      };
    });
    row++;

    const cashFlows = inputs.cashFlows || [-100000, 30000, 35000, 40000, 45000];
    const cashFlowStartRow = row;
    
    for (let i = 0; i < cashFlows.length; i++) {
      const isEvenRow = i % 2 === 0;
      const rowBgColor = isEvenRow ? 'FFF9FAFB' : 'FFFFFFFF';
      
      const periodCell = sheet.getCell(`A${row}`);
      periodCell.value = i;
      periodCell.alignment = { horizontal: 'center' };
      periodCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowBgColor } };
      periodCell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
      
      const cfCell = sheet.getCell(`B${row}`);
      cfCell.value = cashFlows[i];
      cfCell.numFmt = '"$"#,##0.00';
      cfCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowBgColor } };
      cfCell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
      
      // Highlight negative cash flows (initial investment)
      if (cashFlows[i] < 0) {
        cfCell.font = { color: { argb: 'FFDC2626' } }; // Red for outflows
      } else {
        cfCell.font = { color: { argb: 'FF059669' } }; // Green for inflows
      }
      row++;
    }

    row++;
    // IRR Result - Highlighted
    sheet.mergeCells(`A${row}:A${row}`);
    const irrLabelCell = sheet.getCell(`A${row}`);
    irrLabelCell.value = '🎯 IRR Result';
    irrLabelCell.font = { bold: true, size: 12, color: { argb: 'FFFFFFFF' } };
    irrLabelCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF7C3AED' }
    };
    irrLabelCell.alignment = { horizontal: 'center', vertical: 'middle' };
    
    const irrFormula = `IRR(B${cashFlowStartRow}:B${row - 2})`;
    const irrCell = sheet.getCell(`B${row}`);
    irrCell.value = { formula: irrFormula };
    irrCell.numFmt = '0.00%';
    irrCell.font = { bold: true, size: 14, color: { argb: 'FFFFFFFF' } };
    irrCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF7C3AED' }
    };
    irrCell.alignment = { horizontal: 'center' };
    irrCell.border = {
      top: { style: 'medium' },
      bottom: { style: 'medium' },
      left: { style: 'medium' },
      right: { style: 'medium' }
    };
    sheet.getRow(row).height = 26;
    formulas.push({
      cell: `B${row}`,
      formula: irrFormula,
      description: 'Internal Rate of Return'
    });
    row += 2;

    // Decision Box
    sheet.mergeCells(`A${row}:B${row}`);
    const decisionCell = sheet.getCell(`A${row}`);
    decisionCell.value = '✅ Decision: If IRR > Cost of Capital, accept the investment';
    decisionCell.font = { italic: true, size: 11, color: { argb: 'FF374151' } };
    decisionCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF5F3FF' } // Light purple
    };
    decisionCell.alignment = { horizontal: 'center' };
    row++;

    // Set column widths
    sheet.getColumn(1).width = 20;
    sheet.getColumn(2).width = 18;

    return { formulas, nextRow: row + 3 };
  }

  /**
   * Add depreciation schedule
   */
  private addDepreciationSchedule(
    sheet: ExcelJS.Worksheet,
    inputs: Record<string, any>,
    startRow: number
  ): { formulas: FormulaDefinition[]; nextRow: number } {
    const formulas: FormulaDefinition[] = [];
    let row = startRow;

    const assetCost = inputs.assetCost || 100000;
    const salvageValue = inputs.salvageValue || 10000;
    const usefulLife = inputs.usefulLife || 5;
    const method = inputs.method || 'straight-line';

    // Title
    sheet.getCell(`A${row}`).value = `Depreciation Schedule (${method})`;
    sheet.getCell(`A${row}`).font = { bold: true, size: 14 };
    row += 2;

    // Inputs
    sheet.getCell(`A${row}`).value = 'Asset Cost';
    sheet.getCell(`B${row}`).value = assetCost;
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    const costRow = row;
    row++;

    sheet.getCell(`A${row}`).value = 'Salvage Value';
    sheet.getCell(`B${row}`).value = salvageValue;
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    const salvageRow = row;
    row++;

    sheet.getCell(`A${row}`).value = 'Useful Life (years)';
    sheet.getCell(`B${row}`).value = usefulLife;
    const lifeRow = row;
    row += 2;

    // Schedule headers
    sheet.getCell(`A${row}`).value = 'Year';
    sheet.getCell(`B${row}`).value = 'Beginning Balance';
    sheet.getCell(`C${row}`).value = 'Depreciation';
    sheet.getCell(`D${row}`).value = 'Ending Balance';
    sheet.getCell(`E${row}`).value = 'Accumulated Dep.';
    row++;

    const scheduleStartRow = row;
    
    for (let year = 1; year <= usefulLife; year++) {
      sheet.getCell(`A${row}`).value = year;
      
      // Beginning Balance
      if (year === 1) {
        sheet.getCell(`B${row}`).value = { formula: `B${costRow}` };
      } else {
        sheet.getCell(`B${row}`).value = { formula: `D${row - 1}` };
      }
      sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
      
      // Depreciation (straight-line)
      const depFormula = `(B${costRow}-B${salvageRow})/B${lifeRow}`;
      sheet.getCell(`C${row}`).value = { formula: depFormula };
      sheet.getCell(`C${row}`).numFmt = '$#,##0.00';
      
      // Ending Balance
      sheet.getCell(`D${row}`).value = { formula: `B${row}-C${row}` };
      sheet.getCell(`D${row}`).numFmt = '$#,##0.00';
      
      // Accumulated Depreciation
      if (year === 1) {
        sheet.getCell(`E${row}`).value = { formula: `C${row}` };
      } else {
        sheet.getCell(`E${row}`).value = { formula: `E${row - 1}+C${row}` };
      }
      sheet.getCell(`E${row}`).numFmt = '$#,##0.00';
      
      row++;
    }

    formulas.push({
      cell: `C${scheduleStartRow}`,
      formula: `(B${costRow}-B${salvageRow})/B${lifeRow}`,
      description: 'Straight-line depreciation per year'
    });

    return { formulas, nextRow: row + 3 };
  }

  /**
   * Add amortization schedule
   */
  private addAmortizationSchedule(
    sheet: ExcelJS.Worksheet,
    inputs: Record<string, any>,
    startRow: number
  ): { formulas: FormulaDefinition[]; nextRow: number } {
    const formulas: FormulaDefinition[] = [];
    let row = startRow;

    const principal = inputs.loanAmount || 200000;
    const annualRate = inputs.interestRate || 0.05;
    const years = inputs.term || 30;
    const monthlyRate = annualRate / 12;
    const numPayments = years * 12;

    // Title
    sheet.getCell(`A${row}`).value = 'Loan Amortization Schedule';
    sheet.getCell(`A${row}`).font = { bold: true, size: 14 };
    row += 2;

    // Loan details
    sheet.getCell(`A${row}`).value = 'Loan Amount';
    sheet.getCell(`B${row}`).value = principal;
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    const principalRow = row;
    row++;

    sheet.getCell(`A${row}`).value = 'Annual Interest Rate';
    sheet.getCell(`B${row}`).value = annualRate;
    sheet.getCell(`B${row}`).numFmt = '0.00%';
    const rateRow = row;
    row++;

    sheet.getCell(`A${row}`).value = 'Loan Term (years)';
    sheet.getCell(`B${row}`).value = years;
    const termRow = row;
    row++;

    sheet.getCell(`A${row}`).value = 'Monthly Payment';
    const pmtFormula = `PMT(B${rateRow}/12,B${termRow}*12,-B${principalRow})`;
    sheet.getCell(`B${row}`).value = { formula: pmtFormula };
    sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
    sheet.getCell(`B${row}`).font = { bold: true };
    const pmtRow = row;
    formulas.push({
      cell: `B${row}`,
      formula: pmtFormula,
      description: 'Monthly payment calculation using PMT function'
    });
    row += 2;

    // Schedule headers (first 12 months)
    sheet.getCell(`A${row}`).value = 'Month';
    sheet.getCell(`B${row}`).value = 'Beginning Balance';
    sheet.getCell(`C${row}`).value = 'Payment';
    sheet.getCell(`D${row}`).value = 'Principal';
    sheet.getCell(`E${row}`).value = 'Interest';
    sheet.getCell(`F${row}`).value = 'Ending Balance';
    row++;

    const scheduleStart = row;
    
    // Show first 12 months
    for (let month = 1; month <= Math.min(12, numPayments); month++) {
      sheet.getCell(`A${row}`).value = month;
      
      // Beginning Balance
      if (month === 1) {
        sheet.getCell(`B${row}`).value = { formula: `B${principalRow}` };
      } else {
        sheet.getCell(`B${row}`).value = { formula: `F${row - 1}` };
      }
      sheet.getCell(`B${row}`).numFmt = '$#,##0.00';
      
      // Payment
      sheet.getCell(`C${row}`).value = { formula: `B${pmtRow}` };
      sheet.getCell(`C${row}`).numFmt = '$#,##0.00';
      
      // Interest
      sheet.getCell(`E${row}`).value = { formula: `B${row}*(B${rateRow}/12)` };
      sheet.getCell(`E${row}`).numFmt = '$#,##0.00';
      
      // Principal
      sheet.getCell(`D${row}`).value = { formula: `C${row}-E${row}` };
      sheet.getCell(`D${row}`).numFmt = '$#,##0.00';
      
      // Ending Balance
      sheet.getCell(`F${row}`).value = { formula: `B${row}-D${row}` };
      sheet.getCell(`F${row}`).numFmt = '$#,##0.00';
      
      row++;
    }

    return { formulas, nextRow: row + 3 };
  }

  /**
   * Add loan calculation
   */
  private addLoanCalculation(
    sheet: ExcelJS.Worksheet,
    inputs: Record<string, any>,
    startRow: number
  ): { formulas: FormulaDefinition[]; nextRow: number } {
    return this.addAmortizationSchedule(sheet, inputs, startRow);
  }

  /**
   * Create formatted table
   */
  private createTable(sheet: ExcelJS.Worksheet, table: TableDefinition, startRow: number) {
    let row = startRow;

    // Table name
    sheet.getCell(`A${row}`).value = table.name;
    sheet.getCell(`A${row}`).font = { bold: true, size: 12 };
    row += 2;

    // Headers
    table.headers.forEach((header, col) => {
      const cell = sheet.getCell(row, col + 1);
      cell.value = header;
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF0066CC' }
      };
      cell.alignment = { horizontal: 'center' };
    });
    row++;

    // Data
    table.data.forEach((rowData) => {
      rowData.forEach((value, col) => {
        sheet.getCell(row, col + 1).value = value;
      });
      row++;
    });

    // Totals if requested
    if (table.totals) {
      table.headers.forEach((_, col) => {
        const cell = sheet.getCell(row, col + 1);
        if (col === 0) {
          cell.value = 'TOTAL';
          cell.font = { bold: true };
        } else {
          // Try to sum numeric columns
          const startDataRow = startRow + 3;
          cell.value = { formula: `SUM(${this.getColumnLetter(col + 1)}${startDataRow}:${this.getColumnLetter(col + 1)}${row - 1})` };
          cell.font = { bold: true };
        }
      });
    }
  }

  /**
   * Add raw data with automatic header detection
   */
  private addDataWithHeaders(sheet: ExcelJS.Worksheet, data: any[][], startRow: number) {
    let row = startRow;

    // Title
    sheet.getCell(`A${row}`).value = 'Uploaded Data';
    sheet.getCell(`A${row}`).font = { bold: true, size: 12 };
    row += 2;

    // Add data
    data.forEach((rowData, rowIndex) => {
      rowData.forEach((value, colIndex) => {
        const cell = sheet.getCell(row, colIndex + 1);
        cell.value = value;
        
        // Header styling for first row
        if (rowIndex === 0) {
          cell.font = { bold: true };
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFE0E0E0' }
          };
        }
      });
      row++;
    });
  }

  /**
   * Apply standard formatting - Professional styling
   */
  private applyStandardFormatting(sheet: ExcelJS.Worksheet, formatting?: FormattingOptions) {
    // Set default font for entire sheet
    sheet.eachRow((row) => {
      row.eachCell((cell) => {
        if (!cell.font || !cell.font.name) {
          cell.font = { ...cell.font, name: 'Calibri', size: cell.font?.size || 11 };
        }
      });
    });

    // Auto-fit columns with better defaults
    sheet.columns.forEach((column, idx) => {
      if (column && column.values) {
        let maxLength = 12; // Minimum width
        column.values.forEach((value) => {
          if (value) {
            const length = value.toString().length;
            if (length > maxLength) maxLength = length;
          }
        });
        column.width = Math.min(maxLength + 4, 40);
      }
    });

    // Add print settings
    sheet.pageSetup = {
      orientation: 'landscape',
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      margins: {
        left: 0.5,
        right: 0.5,
        top: 0.75,
        bottom: 0.75,
        header: 0.3,
        footer: 0.3
      }
    };

    // Freeze top row
    sheet.views = [{ state: 'frozen', ySplit: 1 }];
  }

  /**
   * Add header to worksheet - Professional branded header
   */
  private addHeader(sheet: ExcelJS.Worksheet) {
    // Logo/Brand row
    sheet.mergeCells('A1:F1');
    const headerCell = sheet.getCell('A1');
    headerCell.value = '🧮 ICAI CAGPT | Financial Analysis Report';
    headerCell.font = { bold: true, size: 18, color: { argb: 'FFFFFFFF' }, name: 'Calibri' };
    headerCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1E40AF' } // Professional blue
    };
    headerCell.alignment = { horizontal: 'center', vertical: 'middle' };
    sheet.getRow(1).height = 40;

    // Generated date row
    sheet.mergeCells('A2:F2');
    const dateCell = sheet.getCell('A2');
    const now = new Date();
    dateCell.value = `Generated: ${now.toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })}`;
    dateCell.font = { size: 10, color: { argb: 'FF6B7280' }, italic: true };
    dateCell.alignment = { horizontal: 'center' };
    dateCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF3F4F6' }
    };
    sheet.getRow(2).height = 22;
  }

  /**
   * Generate summary text
   */
  private generateSummary(
    formulas: FormulaDefinition[],
    tables: string[],
    request: SpreadsheetRequest
  ): string {
    let summary = 'Excel workbook created successfully.\n\n';
    
    if (formulas.length > 0) {
      summary += `Formulas used (${formulas.length}):\n`;
      formulas.forEach((f) => {
        summary += `  • ${f.cell}: ${f.formula}${f.description ? ` - ${f.description}` : ''}\n`;
      });
      summary += '\n';
    }
    
    if (tables.length > 0) {
      summary += `Tables created: ${tables.join(', ')}\n\n`;
    }
    
    summary += 'All formulas are preserved and editable in Excel.';
    return summary;
  }

  /**
   * Convert column number to letter
   */
  private getColumnLetter(col: number): string {
    let letter = '';
    while (col > 0) {
      const mod = (col - 1) % 26;
      letter = String.fromCharCode(65 + mod) + letter;
      col = Math.floor((col - mod) / 26);
    }
    return letter;
  }

  /**
   * Parse uploaded Excel file
   */
  async parseUploadedExcel(fileBuffer: ArrayBuffer | Buffer): Promise<any[][]> {
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(fileBuffer as any);
    
    const sheet = workbook.worksheets[0];
    const data: any[][] = [];
    
    sheet.eachRow((row) => {
      const rowData: any[] = [];
      row.eachCell((cell) => {
        rowData.push(cell.value);
      });
      data.push(rowData);
    });
    
    return data;
  }

  /**
   * Extract spreadsheet preview data from workbook for UI display
   * Includes formulas as visible text and cell styles
   */
  extractSpreadsheetPreview(workbook: ExcelJS.Workbook): SpreadsheetPreviewData {
    const sheets: SheetPreview[] = [];
    
    workbook.worksheets.forEach((worksheet) => {
      const data: (string | number | null)[][] = [];
      const styles: CellStylePreview[][] = [];
      const merges: MergeInfo[] = [];
      const formulas: string[] = [];
      
      // Collect merge information
      worksheet.model.merges?.forEach((mergeRange) => {
        const [start] = mergeRange.split(':');
        const startMatch = start.match(/([A-Z]+)(\d+)/);
        if (startMatch) {
          const col = this.columnLetterToNumber(startMatch[1]) - 1;
          const row = parseInt(startMatch[2]) - 1;
          const [, end] = mergeRange.split(':');
          const endMatch = end?.match(/([A-Z]+)(\d+)/);
          if (endMatch) {
            const endCol = this.columnLetterToNumber(endMatch[1]) - 1;
            const endRow = parseInt(endMatch[2]) - 1;
            merges.push({
              row,
              col,
              rowspan: endRow - row + 1,
              colspan: endCol - col + 1
            });
          }
        }
      });
      
      // Extract cell data and styles
      const maxRow = Math.min(worksheet.rowCount, 100); // Limit preview to 100 rows
      for (let rowIndex = 1; rowIndex <= maxRow; rowIndex++) {
        const row = worksheet.getRow(rowIndex);
        const rowData: (string | number | null)[] = [];
        const rowStyles: CellStylePreview[] = [];
        
        const maxCol = Math.min(worksheet.columnCount, 26); // Limit to 26 columns
        for (let colIndex = 1; colIndex <= maxCol; colIndex++) {
          const cell = row.getCell(colIndex);
          
          // Get cell value - show formula if present
          let cellValue: string | number | null = null;
          if (cell.formula) {
            // Show formula in preview with = prefix
            cellValue = `=${cell.formula}`;
            formulas.push(`${this.getColumnLetter(colIndex)}${rowIndex}: =${cell.formula}`);
          } else if (cell.value !== null && cell.value !== undefined) {
            if (typeof cell.value === 'object' && 'formula' in cell.value) {
              cellValue = `=${(cell.value as any).formula}`;
              formulas.push(`${this.getColumnLetter(colIndex)}${rowIndex}: =${(cell.value as any).formula}`);
            } else if (typeof cell.value === 'object' && 'richText' in cell.value) {
              // Handle rich text
              cellValue = (cell.value as any).richText.map((rt: any) => rt.text).join('');
            } else if (typeof cell.value === 'object') {
              cellValue = String(cell.value);
            } else {
              cellValue = cell.value as string | number;
            }
          }
          
          rowData.push(cellValue);
          
          // Extract styles
          const cellStyle: CellStylePreview = {};
          if (cell.font) {
            cellStyle.font = {
              bold: cell.font.bold,
              italic: cell.font.italic,
              color: cell.font.color?.argb?.slice(2), // Remove alpha
              size: cell.font.size
            };
          }
          if (cell.fill && cell.fill.type === 'pattern' && cell.fill.fgColor) {
            cellStyle.background = cell.fill.fgColor.argb?.slice(2);
          }
          if (cell.alignment) {
            cellStyle.align = cell.alignment.horizontal as 'left' | 'center' | 'right';
          }
          if (cell.border) {
            cellStyle.border = {
              top: !!cell.border.top,
              bottom: !!cell.border.bottom,
              left: !!cell.border.left,
              right: !!cell.border.right
            };
          }
          rowStyles.push(cellStyle);
        }
        
        data.push(rowData);
        styles.push(rowStyles);
      }
      
      sheets.push({
        name: worksheet.name,
        data,
        styles,
        merges,
        formulas
      });
    });
    
    return {
      sheets,
      metadata: {
        title: workbook.title || 'ICAI CAGPT Generated Workbook',
        description: workbook.description,
        sheetCount: workbook.worksheets.length
      }
    };
  }
  
  /**
   * Convert column letter to number (A=1, B=2, etc.)
   */
  private columnLetterToNumber(letter: string): number {
    let result = 0;
    for (let i = 0; i < letter.length; i++) {
      result = result * 26 + (letter.charCodeAt(i) - 64);
    }
    return result;
  }
}

// Type definitions for spreadsheet preview
export interface SpreadsheetPreviewData {
  sheets: SheetPreview[];
  metadata?: {
    title?: string;
    description?: string;
    sheetCount?: number;
    calculations?: string[];
  };
}

export interface SheetPreview {
  name: string;
  data: (string | number | null)[][];
  styles?: CellStylePreview[][];
  merges?: MergeInfo[];
  formulas?: string[];
}

export interface CellStylePreview {
  font?: {
    bold?: boolean;
    italic?: boolean;
    color?: string;
    size?: number;
  };
  background?: string;
  align?: 'left' | 'center' | 'right';
  border?: {
    top?: boolean;
    bottom?: boolean;
    left?: boolean;
    right?: boolean;
  };
}

export interface MergeInfo {
  row: number;
  col: number;
  rowspan: number;
  colspan: number;
}

export const excelOrchestrator = new ExcelOrchestrator();
